### PR TITLE
add operational tools for build, run, clean and debug

### PR DESCRIPTION
**Pull request by theikalman**

### CODE REVIEW

**Review by tamzidan — COMMENTED** [review]
what is this code useful for?

**Comment by theikalman** [comment]
This will add any operational tools to make it easy to run and validate the service @tamzidan . The goals is to use:
- `make build` to build all services (backend, front-end) into itsown docker images so the it will be easier to deploy to server
- `make run` to run all the services locally with only dependencies is docker
- `make clean` to clean-up all any generated resources

Here is an example in [nodejs project](https://github.com/nodejs/node/blob/main/Makefile). It was using bash script and you can learn bash script [here](https://www.gnu.org/software/bash/manual/bash.html). The script often used by developer around tooling to make development easier.

This PR is subject to change, I probably will try to implements it with npm script such as [this one](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/development/scripts.md) as this might be closer to what you used to have on your arsenal-tools. The concept were the same, to simplify any operational command.

**Comment by tamzidan** [comment]
> This will add any operational tools to make it easy to run and validate the service @tamzidan . The goals is to use:
> 
> * `make build` to build all services (backend, front-end) into itsown docker images so the it will be easier to deploy to server
> * `make run` to run all the services locally with only dependencies is docker
> * `make clean` to clean-up all any generated resources
> 
> Here is an example in [nodejs project](https://github.com/nodejs/node/blob/main/Makefile). It was using bash script and you can learn bash script [here](https://www.gnu.org/software/bash/manual/bash.html). The script often used by developer around tooling to make development easier.
> 
> This PR is subject to change, I probably will try to implements it with npm script such as [this one](https://github.com/swagger-api/swagger-ui/blob/HEAD/docs/development/scripts.md) as this might be closer to what you used to have on your arsenal-tools. The concept were the same, to simplify any operational command.

okay, so is everything done? and can the application be run?

**Comment by theikalman** [comment]
This is actually not ready yet. I am busy this week, there's a release happening, so I'll be revisit this one later next week.

**Comment by tamzidan** [comment]
> This is actually not ready yet. I am busy this week, there's a release happening, so I'll be revisit this one later next week.

okee...

**Pull request merged**
